version: "3"

networks:
  loki:

services:
  app.java:
    image: konstantinkhomutov/devops-labs
    ports:
      - "8080:8080"
    networks:
      - loki
    volumes:
      - /logs/:/var/log/

  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config/:/etc/loki/
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /logs/:/var/log
      - ./promtail-config/:/etc/promtail/
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.5.6
    ports:
      - "3000:3000"
    networks:
      - loki