---

- name: Install pip
  package:
    name: "python3-pip"
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install Docker-compose
  pip:
    name: docker-compose
    state: present

