apiVersion: v1
kind: Secret
metadata:
  name: user-pass
  namespace: default
  labels:
    app: java-app
type: Opaque
data:
  password1: {{ .Values.password1 | b64enc | quote }}
  username1: {{ .Values.username1 | b64enc | quote }}
