# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  	# Specifying the box we wish to use
  	 config.vm.box = "emessiha/ubuntu64-java"
     config.vm.box_version = "1.0.0"
     config.ssh.insert_key = false
     config.ssh.forward_agent = true
     config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
     config.vm.synced_folder ".", "/vagrant", disabled: true
  	# Adding Bridged Network Adapter
  	config.vm.network "public_network"
  	# Iterating the loop for three times
  	(1..3).each do |i|
  		# Defining VM properties
  		config.vm.define "java_vm#{i}" do |node|
  			# Specifying the provider as VirtualBox and naming the VM's
  			config.vm.provider "virtualbox" do |node|
  				# The VM will be named as java_vm{i}
  				node.name = "java_vm#{i}"
  			end
  		end
  	end
  end